# this file is managed by dry-rb/devtools project

version: "2"

prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/dry-rb/devtools/shared/.rubocop.yml"
    path: ".rubocop.yml"

exclude_patterns:
  - "benchmarks/"
  - "examples/"
  - "spec/"

plugins:
  rubocop:
    enabled: true
